"""
Grow Hiligaynon recognition coverage from the curated phrase table.

Ilonggo speakers vary a phrase in ways fuzzy matching handles badly, because the
change is structural rather than a single mistyped letter:

    nagaubo / gaubo / ginaubo / nag-ubo      (aspect prefixes)
    sakit sang tiyan / sakit tiyan            (dropped particle)
    mag-ihi / mag ihi / magihi                (hyphen conventions)
    nagalipong ako / nagalipong ko            (pronoun choice)

This generates those variants, then keeps only the ones that are BOTH currently
unrecognised AND unambiguous (they must not already resolve to a different
symptom). Survivors are written to data/nlp/hiligaynon_symptom_variants.json,
which the analyzer merges into its translation map.

Run:
    python scripts/data/expand_hiligaynon_variants.py
    python scripts/data/expand_hiligaynon_variants.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "ai_service"))

PHRASE_FILE = ROOT / "data" / "nlp" / "hiligaynon_symptom_phrases.json"
VARIANT_FILE = ROOT / "data" / "nlp" / "hiligaynon_symptom_variants.json"

ASPECT_PREFIXES = ("naga", "gina", "nag", "ga", "gin")
PARTICLES = ("ang", "sang", "nga", "sa")


def phrase_variants(phrase: str) -> set[str]:
    """Plausible ways a patient writes the same phrase."""
    out: set[str] = set()
    words = phrase.split()

    for index, word in enumerate(words):
        for prefix in ASPECT_PREFIXES:
            if not word.startswith(prefix) or len(word) <= len(prefix) + 2:
                continue
            stem = word[len(prefix) :].lstrip("-")
            for other in ASPECT_PREFIXES:
                if other == prefix:
                    continue
                for joined in (f"{other}{stem}", f"{other}-{stem}"):
                    swapped = list(words)
                    swapped[index] = joined
                    out.add(" ".join(swapped))

    for particle in PARTICLES:
        dropped = re.sub(rf"(?<!\w){particle}(?!\w)", " ", phrase)
        dropped = re.sub(r"\s+", " ", dropped).strip()
        if dropped and dropped != phrase and len(dropped.split()) >= 2:
            out.add(dropped)

    if "-" in phrase:
        out.add(phrase.replace("-", " "))
        out.add(phrase.replace("-", ""))

    if phrase.endswith(" ako"):
        base = phrase[:-4]
        out.update({base, f"{base} ko", f"{base} gid"})
    elif phrase.endswith(" ko"):
        base = phrase[:-3]
        out.update({base, f"{base} ako", f"{base} gid"})
    else:
        out.update({f"{phrase} ako", f"{phrase} ko", f"{phrase} gid"})

    if not phrase.startswith("may "):
        out.add(f"may {phrase}")

    cleaned = {re.sub(r"\s+", " ", v).strip() for v in out}
    return {v for v in cleaned if v and v != phrase and len(v) >= 5}


def main() -> int:
    parser = argparse.ArgumentParser(description="Expand Hiligaynon symptom variants")
    parser.add_argument("--dry-run", action="store_true", help="Report without writing.")
    args = parser.parse_args()

    from analyzer import translate_hiligaynon
    from disease_predictor import extract_model_symptoms

    payload = json.loads(PHRASE_FILE.read_text(encoding="utf-8"))
    phrases: dict[str, list[str]] = payload.get("phrases") or {}

    def detect(text: str) -> set[str]:
        return set(extract_model_symptoms(translate_hiligaynon(text)))

    accepted: dict[str, list[str]] = {}
    already = 0
    ambiguous = 0

    for key, variants in phrases.items():
        for phrase in variants:
            for candidate in sorted(phrase_variants(phrase)):
                found = detect(candidate)
                if key in found:
                    already += 1
                    continue
                # Never claim a variant that already means another symptom.
                if found:
                    ambiguous += 1
                    continue
                accepted.setdefault(key, [])
                if candidate not in accepted[key]:
                    accepted[key].append(candidate)

    total = sum(len(v) for v in accepted.values())
    print(f"Curated phrases:      {sum(len(v) for v in phrases.values())}")
    print(f"Already recognised:   {already}")
    print(f"Skipped (ambiguous):  {ambiguous}")
    print(f"New variants kept:    {total} across {len(accepted)} symptoms")

    if args.dry_run:
        for key in sorted(accepted)[:10]:
            print(f"  {key}: {accepted[key][:4]}")
        return 0

    VARIANT_FILE.write_text(
        json.dumps(
            {
                "_comment": [
                    "Generated by scripts/data/expand_hiligaynon_variants.py.",
                    "Prefix, particle, hyphen and pronoun variants of the curated phrases",
                    "that the pipeline could not otherwise recognise. Every entry was",
                    "checked to not already mean a different symptom.",
                    "Regenerate after editing hiligaynon_symptom_phrases.json.",
                ],
                "variants": {key: sorted(vals) for key, vals in sorted(accepted.items())},
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {VARIANT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
