-- Urgent Follow-up Workflow: post-consultation NLP-triaged follow-up cases
CREATE TABLE IF NOT EXISTS urgent_followup_cases (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    patient_id INT(11) UNSIGNED NOT NULL,
    provider_id INT(11) UNSIGNED NOT NULL,
    original_consultation_id INT(11) UNSIGNED NOT NULL,
    triage_result_id INT(11) UNSIGNED NULL,
    previous_chief_complaint TEXT NULL,
    updated_chief_complaint TEXT NOT NULL,
    previous_consult_date DATE NULL,
    triage_classification VARCHAR(32) NOT NULL DEFAULT 'NON_URGENT',
    triage_display VARCHAR(32) NOT NULL DEFAULT 'NON-URGENT',
    confidence_score DECIMAL(5,2) NULL,
    assessment_payload JSON NULL,
    status ENUM(
        'pending',
        'waiting',
        'accepted',
        'in_consultation',
        'completed',
        'booked',
        'emergency_referral',
        'cancelled'
    ) NOT NULL DEFAULT 'pending',
    queue_priority TINYINT UNSIGNED NOT NULL DEFAULT 3 COMMENT '1=EMERGENCY, 2=URGENT, 3=NON_URGENT',
    provider_available_at_submit TINYINT(1) NOT NULL DEFAULT 0,
    can_start_immediately TINYINT(1) NOT NULL DEFAULT 0,
    reassigned_from_provider_id INT(11) UNSIGNED NULL,
    followup_consultation_id INT(11) UNSIGNED NULL,
    referral_id INT(11) UNSIGNED NULL,
    notified_at DATETIME NULL,
    accepted_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_ufc_provider_status (provider_id, status),
    KEY idx_ufc_patient (patient_id),
    KEY idx_ufc_priority_created (queue_priority, created_at),
    KEY idx_ufc_original_consult (original_consultation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
